### ISSUE TITLE
Newsletter sign up form on iPhone6

### ISSUE THREAD

**Issue by ghost** [BitCraftIO/bitcraft.io#9]
Newsletter sign up is not sticking to bottom of view.

![iphone-newsletter-signup](https://user-images.githubusercontent.com/26121284/42285985-4b5b3202-7f7f-11e8-8578-ee88e7c69f6a.gif)

**Comment by ferrerluis** [comment]
Last commit seems to have fixed this. Thanks for letting me know!!!
